module.exports = {
  basiliskOptions: require("./basilisk"),
  bifrostOptions: require("./bifrost"),
  crustOptions: require("./crust"),
  karuraOptions: require("./karura"),
  khalaOptions: require("./khala"),
  kintsugiOptions: require("./kintsugi"),
  polkadexOptions: require("./polkadex"),
  soraOptions: require("./sora"),
  crabOptions: require("./crab"),
  centrifugeOptions: require("./centrifuge"),
  altairOptions: require("./altari"),
  zeitgeistOptions: require("./zeitgeist"),
  shidenOptions: require("./shiden"),
}
